AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:

  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-ceportal-doc-storage

  FileApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: file-transfer-api
      StageName: prod
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  UploadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload-file-handler
      Handler: uploadFile.handler
      CodeUri: .
      Environment:
        Variables:
          BUCKET_NAME: !Ref FileStorageBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            RestApiId: !Ref FileApi

  DownloadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: download-file-handler
      Handler: downloadFile.handler
      CodeUri: .
      Environment:
        Variables:
          BUCKET_NAME: !Ref FileStorageBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        DownloadApi:
          Type: Api
          Properties:
            Path: /download
            Method: GET
            RestApiId: !Ref FileApi
